current_dir = "E:\\二次絵保管庫\\"
file_list_csv = "files\\file_list.txt"
illustrator_csv = "files\\illustrator.csv"
sleep_exception = "20"
illustrator_buttom_sec = "5"
illustrator_interval = "4"
illustid_interval = "1"
get_illust_time = "2"
get_manga_page_time = "1"

log_file = "files\\kyokou_log.txt"